version: '3.4'

services:
  masglobal.portal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  masglobal.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

networks:
  default:
    external:
      name: nat

